- hosts: ["namenode-active","namenode-standby","datanode1","datanode2"]
  tasks:
  - name: "mkdir data directory"
    shell: |
      rm -rf /data
      mkdir -p /data/hdfs/namenode
      mkdir -p /data/hdfs/datanode
      mkdir -p /data/hdfs/journalnode
      mkdir -p /data/yarn/nodemanager
      mkdir -p /data/yarn/resourcemanager
      mkdir -p /opt/hadoop/logs
      mkdir -p /opt/hadoop/pids

  - name: "copy config files"
    copy:
      src: "/root/ansible/conf/hadoop/{{ item }}"
      dest: "/opt/hadoop/etc/hadoop/{{ item }}"
    with_items:  
    - core-site.xml  
    - yarn-site.xml 
    - yarn-env.sh  
    - mapred-site.xml  
    - hdfs-site.xml
    - hadoop-env.sh  
    - workers
