apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddarahakitshop-main-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddarahakitshop-main
  template:
    metadata:
      labels:
        app: ddarahakitshop-main
    spec:
      containers:
        - name: ddarahakitshop-main
          image: ddarahakit/ddarahakitshop-main:0.2
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: my-secret